/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Design = IDL.Record({
  'id' : IDL.Text,
  'weddingDate' : IDL.Text,
  'venue' : IDL.Text,
  'templateId' : IDL.Text,
  'createdAt' : Time,
  'partner2Name' : IDL.Text,
  'rsvpDetails' : IDL.Text,
  'updatedAt' : Time,
  'message' : IDL.Text,
  'partner1Name' : IDL.Text,
  'designName' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteDesign' : IDL.Func([IDL.Text], [], []),
  'getAllDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
  'getAllDesignsSortedByName' : IDL.Func([], [IDL.Vec(Design)], ['query']),
  'getDesign' : IDL.Func([IDL.Text], [Design], ['query']),
  'saveDesign' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'updateDesign' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Design = IDL.Record({
    'id' : IDL.Text,
    'weddingDate' : IDL.Text,
    'venue' : IDL.Text,
    'templateId' : IDL.Text,
    'createdAt' : Time,
    'partner2Name' : IDL.Text,
    'rsvpDetails' : IDL.Text,
    'updatedAt' : Time,
    'message' : IDL.Text,
    'partner1Name' : IDL.Text,
    'designName' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteDesign' : IDL.Func([IDL.Text], [], []),
    'getAllDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
    'getAllDesignsSortedByName' : IDL.Func([], [IDL.Vec(Design)], ['query']),
    'getDesign' : IDL.Func([IDL.Text], [Design], ['query']),
    'saveDesign' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'updateDesign' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };