/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Time = IDL.Int;
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'messages' : IDL.Vec(Message),
  'createdAt' : Time,
  'updatedAt' : Time,
});

export const idlService = IDL.Service({
  'deleteSession' : IDL.Func([IDL.Nat], [], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getAllSessionsSortedById' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getSession' : IDL.Func([IDL.Nat], [Session], ['query']),
  'saveSession' : IDL.Func([IDL.Nat, IDL.Vec(Message)], [], []),
  'updateSession' : IDL.Func([IDL.Nat, IDL.Vec(Message)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Time = IDL.Int;
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'messages' : IDL.Vec(Message),
    'createdAt' : Time,
    'updatedAt' : Time,
  });
  
  return IDL.Service({
    'deleteSession' : IDL.Func([IDL.Nat], [], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getAllSessionsSortedById' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getSession' : IDL.Func([IDL.Nat], [Session], ['query']),
    'saveSession' : IDL.Func([IDL.Nat, IDL.Vec(Message)], [], []),
    'updateSession' : IDL.Func([IDL.Nat, IDL.Vec(Message)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };