/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Design {
  'id' : string,
  'weddingDate' : string,
  'venue' : string,
  'templateId' : string,
  'createdAt' : Time,
  'partner2Name' : string,
  'rsvpDetails' : string,
  'updatedAt' : Time,
  'message' : string,
  'partner1Name' : string,
  'designName' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'deleteDesign' : ActorMethod<[string], undefined>,
  'getAllDesigns' : ActorMethod<[], Array<Design>>,
  'getAllDesignsSortedByName' : ActorMethod<[], Array<Design>>,
  'getDesign' : ActorMethod<[string], Design>,
  'saveDesign' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    string
  >,
  'updateDesign' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];